discourse/discourse-table-builder

javascripts/discourse/components/spreadsheet-editor.js
settings.yml

This also makes sure we don't need any CSP rules for the loaded JS files.

FIX: Use local theme files for external libs

---

locales/en.yml

To add consistency with naming used in other areas of the composer, this PR changes the label of the primary button from  <kbd>Update Table</kbd> to <kbd>Save Edit</kbd>

UX: Change edit modal primary button label to `Save Edit`

---

javascripts/discourse/components/spreadsheet-editor.js
locales/en.yml
scss/modal/insert-table-modal.scss
scss/theme/jspreadsheet-theme.scss

- **Before**
- <img width="500" alt="Screen Shot 2022-08-10 at 12 34 38 PM" src="https://user-images.githubusercontent.com/30090424/184004929-3644ef48-e90a-4a0c-b636-bb5f131962ac.png">
- **After**
- <img width="500" alt="Screen Shot 2022-08-10 at 12 35 36 PM" src="https://user-images.githubusercontent.com/30090424/184004864-2b5a4f88-ad1b-4120-8580-fae593d170bb.png">

UX: Wrap words instead of dynamic widths and align left

---

javascripts/discourse/api-initializers/table-editor.js

When posts include a content as well as a `<table>` element for other purposes such as with the `discourse-calendar` plugin. These tables get decorated with the <kbd>Edit Table</kbd> button like so:
This **PR resolves this issue** by first querying for selectors with the `.md-table` class.

FIX: Edit Table button appearing in all `<table>` elements

---

javascripts/discourse/components/spreadsheet-editor.js

Now that all of our singletons have been converted to true Ember Services, we can remove our custom `discourse/component/glimmer` superclass and use explicit injection

DEV: Update `SpreadsheetEditor` to use `@glimmer/component`

---

javascripts/discourse/components/spreadsheet-editor.js
locales/en.yml
scss/modal/insert-table-modal.scss

With tables with only a few columns (say 3-4), I noticed that manipulating the size of the columns was jumpy and not always intuitive. It feels easier to always default to a large modal window, that way fiddling with column widths is less necessary. 
What do you think @keegangeorge?

UX: Default to wide tables

---

javascripts/discourse/components/spreadsheet-editor.js

When copy/pasting things from Numbers, I ran into an issue where the post would not save at all and a 500 error would be raised: 
```
Discourse::InvalidParameters (string contains null byte)
```
The fix replaces all null character, markdown-it does a similar thing: 
https://github.com/discourse/discourse/blob/main/vendor/assets/javascripts/markdown-it.js#L3638-L3640 
Would be nice to add a test for this part of the component in a followup PR (basically checking that original raw gets replaced by jexcel's raw).

FIX: Strip null characters

---

javascripts/discourse/api-initializers/table-editor.js

This PR applies compatibility updates to get rid of the following warnings:
```bash
deprecated.js:35 [THEME 2 'Table Builder'] Deprecation notice: "site:main" is deprecated, use "service:site" instead (deprecated since Discourse 2.9.0.beta7) (removal in Discourse 3.0.0)
e.default @ deprecated.js:35
deprecated.js:35 [THEME 2 'Table Builder'] Deprecation notice: "site-settings:main" is deprecated, use "service:site-settings" instead (deprecated since Discourse 2.9.0.beta7) (removal in Discourse 3.0.0)
```

DEV: Update `site` and `siteSettings` references

---

javascripts/discourse/components/spreadsheet-editor.js

This PR adds a unique filename when exporting a table using the <kbd>Save As</kbd> button in the spreadsheet's context menu.
- If exporting a table for a new post, the filename will be `post-table-export.csv`
- If editing a table for an existing post and exporting, the filename will include the post number in the filename `post-${postNumber}-table-export`  i.e. `post-5-table-export.csv`

FEATURE: Add unique filename for table exports

---

scss/modal/insert-table-modal.scss

As per [feedback](https://meta.discourse.org/t/table-builder/236016/6?u=keegan), this PR improves the sizing of the table builder's max modal width.
It prevents the modal on very large screens from spanning the full width. While still maintaining a large width based on feedback discovered from [previous PR](https://github.com/discourse/discourse-table-builder/pull/16).
**Before**:
(XL Desktop Full Screen)
**After**:
(XL Desktop Full Screen)
(Small Desktop Full Screen)

UX: Improve table modal max width for larger screens

---

javascripts/discourse/api-initializers/table-editor.js

This PR adds compatibility with [Category sidebars](https://github.com/discourse/discourse-category-sidebars). Since the category sidebar component adds a decorated post widget in the topic list view, the table builder must ensure a helper and post exist before attempting to make decorations.
Thus, this PR adds a check for if either the widget helper or post are present before attempting to decorate the post.

FIX: Ensure helper or post exist before decorations

---

javascripts/discourse/api-initializers/table-editor.js

This reverts commit 2896c69a727f18414afe2d4799cde5efbb0c1293.
The change is not necessary as the problem was actually the result of the category sidebars component. The fix for that is found in this PR → https://github.com/discourse/discourse-category-sidebars/pull/6

Revert "DEV: Ensure helper or post exist before decorations (#27)"

---

javascripts/discourse/api-initializers/table-editor.js
scss/post/table-edit-decorator.scss

This PR makes the text of the edit table button not selectable so that when post's contents are copied, the edit table label does not copy over as well.

FIX: Make edit table button text not selectable

---

locales/en.yml

When opening the **Edit Table** modal the primary action button has the label <kbd>✏️ Save Edit</kbd>. This label is causing confusion for some, thinking that the button serves two actions (edit or save) rather than meaning to "Save the edit".
As a result, this PR changes the button's label simply to <kbd>✏️ Save</kbd> to avoid confusion.

UX: Reduce confusion when editing tables

---

javascripts/discourse-table-builder/lib/utilities.js
javascripts/discourse/components/spreadsheet-editor.js
test/unit/lib/utilities-test.js

Previously, the regex was catching uploads as well as tables.
This change ensures only strict tables are matched by requiring that matches start with the pipe character.
Also adds a unit test for `findTableRegex` to describe the expected behaviour of the helper.

FIX: do not edit wrong table when post has uploads

---

assets/vendor/jsuites.js
build.bash
scss/vendor/jsuites.scss

This PR updates the bash script to reflect changes in jSuites library URL, fetches the latest libraries thereby updating jSuites to version `4.17.5`.
After fetching the latest scripts and stylesheet, a minor manual change was made in line `1762` changing:
```diff
-    box-shadow: 1px 1px 2px rgb(0 0 0 / 10%);
+    box-shadow: 1px 1px 2px rgba(0, 0, 0, 0.1);
```
This is necessary because the library is using the new CSS standard of `rgb`, however, this is not yet supported in SASS compilation, so `rgba` needs to be used here instead.

DEV: Update vendor assets

---

javascripts/discourse-table-builder/lib/utilities.js
test/unit/lib/utilities-test.js

Pasting text with line breaks into the table UI results in incorrectly generated table markdown.
This fix strips line breaks from text during table markdown generation.
https://user-images.githubusercontent.com/849886/221232073-f74eb460-9515-428e-8918-6d664d1ba420.mov
https://user-images.githubusercontent.com/849886/221232274-687aca8e-f6a1-49e6-9def-b41e6f535f96.mov
- Replace line breaks with `<br>` during table creation and `<b>` with line breaks when instantiating Jspreadsheet  with table data
-  Setting Jspreadsheet `wordWrap`  option to `false` auto replaces line breaks on paste

FIX: Remove line breaks from cell data

---

javascripts/discourse/api-initializers/table-editor.js

Along with the core change: https://github.com/discourse/discourse/pull/20820 to make the expand button icon-only, this PR also makes the table builder's edit button icon-only to maximize space. The label is now moved to the title attribute so it appears in the default HTML tooltip.

UX: Make table builder edit button icon-only

---

javascripts/discourse/api-initializers/table-editor.js
javascripts/discourse/components/spreadsheet-editor.js
javascripts/discourse/templates/modal/insert-table-modal.hbs

We were relying on the `event.target`, and sometimes that target was not the button element with the `table-id` data attribute, but the svg. 
This PR makes a few changes: 
- renames `tableId` to `tableIndex`
- passes the index as part of the attributes to the `generateModal` function

FIX: Table editing sometimes not working

---

javascripts/discourse/pre-initializers/add-module-shims.js

The changes in 8599bfcaff34993ab9e5e7d90edaabb1471a99b6 needed to be applied precisely in-step with the core changes from https://github.com/discourse/discourse/pull/23148. This is impossible to guarantee with a theme - `.discourse-compatibility` does not give us enough precision. So instead, we need some temporary backwards-compatibility shims so that the new relative-import paths still work on old discourse.

DEV: Introduce backwards-compat shims for older Discourse core

---

javascripts/discourse/components/spreadsheet-editor.hbs
javascripts/discourse/components/spreadsheet-editor.js
scss/modal/insert-table-modal.scss
scss/theme/jspreadsheet-theme.scss

This PR makes the table creator/editor modal be full width/height. This makes it easier for working with the spreadsheet editor and also helps prevent clicking outside and having to start over. This PR also moves the "Edit Reason" field from within the modal body to the modal footer.

UX: Full width/height modal

---

javascripts/discourse-table-builder/lib/locale-mapping.js
locales/en.yml

This PR removes a locale the locale `showingPage` taken from the jSpreadsheet library. In our usage of table builder, we are not using pagination and this locale is not needed.

DEV: Remove unused pagination locale

---

javascripts/discourse/components/spreadsheet-editor.hbs
javascripts/discourse/components/spreadsheet-editor.js
locales/en.yml

This PR adds a confirmation dialog box when attempting to close the table builder/editor when there are unsaved changes.
This will help prevent accidental closes by pressing <kbd>Esc</kbd> on the keyboard, or accidentally clicking the Cancel or ✖️ button.
When no changes have been made, cancelling or escaping will close without showing a dialog box.
https://github.com/discourse/discourse-table-builder/assets/30090424/24044c13-da8c-4f62-a79a-1689ea6b8c61

UX: Confirm before closing unsaved changes

---

javascripts/discourse/components/spreadsheet-editor.hbs

**This PR resolves the following deprecation warning:**
```js
Deprecation notice: `<DPopover />` is deprecated. Use `<DTooltip />` or the `tooltip` service instead. [deprecation id: discourse.d-popover]
```

DEV: Update `DPopover` to `DTooltip` to remove deprecation warning

---

about.json

Removes min/max Discourse version to prevent updating.

FIX: `about.json` error when updating
